<?php

/**
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2004-present Agence Dn'D
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.dnd.fr/
 */

use Didomi\ConsentManagement\ViewModel\UniversalTag;
use Magento\Cookie\Helper\Cookie;
use Magento\GoogleAnalytics\Block\Ga;
use Magento\GoogleAnalytics\Helper\Data;

/** @var Ga $block */

/** @var UniversalTag $viewModel */
$viewModel = $block->getDidomiConsentManagementGaTagViewModel();
$accountId = $block->getConfig(Data::XML_PATH_ACCOUNT);
?>
<!-- BEGIN GOOGLE ANALYTICS CODE -->
<script type="text/x-magento-init">
{
    "*": {
        "didomiConsent": {
            "isCookieRestrictionModeEnabled": <?= (int)$block->isCookieRestrictionModeEnabled() ?>,
            "currentWebsite": <?= (int)$block->getCurrentWebsiteId() ?>,
            "cookieName": "<?= /* @noEscape */ Cookie::IS_USER_ALLOWED_SAVE_COOKIE ?>",
            "ordersTrackingData": <?= /* @noEscape */ json_encode($block->getOrdersTrackingData()) ?>,
            "pageTrackingData": <?= /* @noEscape */ json_encode($block->getPageTrackingData($accountId)) ?>,
            "isDidomiUniversalAnalyticsVendorEnabled": <?= (int)$viewModel->isDidomiConditionGa() ?>,
            "didomiUniversalAnalyticsVendorId": "<?= /* @noEscape */ $viewModel->retrieveVendorId() ?>"
        }
    }
}
</script>
<!-- END GOOGLE ANALYTICS CODE -->
