<?php
/**
 * @package   Didomi\ConsentManagement\view\footer
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2004-present Agence Dn'D
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.dnd.fr/
 */

use Didomi\ConsentManagement\ViewModel\FooterScript;
use Magento\Framework\View\Element\Template;

/** @var Template $block */

/** @var FooterScript $viewModel */
$viewModel = $block->getDidomiConsentementManagementFooterScriptViewModel();
/** @var string $label */
$label = $viewModel->retrieveConsentChoiceLinkLabel();
?>

<?php if ($viewModel->isDidomiEnable() && $viewModel->isDidomiDisplayConsentLinkFooter()): ?>
<li class="nav item">
    <a href="javascript:Didomi.preferences.show()"><?= $label ?></a>
</li>
<?php endif ?>
