<?php

/**
 * @author    Agence Dn'D <contact@dnd.fr>
 * @copyright 2004-present Agence Dn'D
 * @license   https://opensource.org/licenses/osl-3.0.php  Open Software License (OSL 3.0)
 * @link      https://www.dnd.fr/
 */

use Didomi\ConsentManagement\ViewModel\HeadScript;
use Magento\Framework\View\Element\Template;

/** @var Template $block */

/** @var HeadScript $viewModel */
$viewModel = $block->getDidomiConsentManagementHeadScriptViewModel()
?>

<?php if ($viewModel->isDidomiEnable() && $viewModel->retrieveConsentNotice() !== null): ?>
    <?= $viewModel->retrieveConsentNotice() ?>
<?php endif ?>
